{{- if .Values.presidioAnalyzer.enabled -}}
{{- if .Values.presidioAnalyzer.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "presidioAnalyzer.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.presidioAnalyzer.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.presidioAnalyzer.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.presidioAnalyzer.serviceAccount.automountServiceAccountToken }}
{{- end }}
{{- end }}
