extraArgs:
  - "--namespaces=romain"
  - "--resources=daemonsets,deployments,horizontalpodautoscalers,jobs,namespaces,nodes,persistentvolumeclaims,persistentvolumes,pods,replicasets,statefulsets,services,ingresses,secrets"