apiVersion: v2
name: langsmith
maintainers:
  - name: Ankush
    email: ankush@langchain.dev
description: Helm chart to deploy the langsmith application and all services it depends on.
type: application
version: 0.16.0-rc.9
appVersion: "0.16.10rc1"
dependencies:
  - name: juicefs-csi-driver
    version: 0.31.4
    repository: https://juicedata.github.io/charts/
    condition: config.sandboxes.enabled
