config:
  langsmithLicenseKey: "<your license key>"
  apiKeySalt: "jeaav27DD6y3FiVT8/x98HPA2YZlPAdVjJbGdpCMZOk="
  authType: mixed
  namespace: john-security-testing
  basicAuth:
    enabled: true
    initialOrgAdminEmail: "john@langchain.dev" # Change this to your admin email address
    initialOrgAdminPassword: "SE12cure-password" # Must be at least 12 characters long and have at least one lowercase, uppercase, and symbol
    jwtSecret: KV8SNNgWVnhydOJeTvybNEb2rqHrFd97MVzHfNHGbgo= # A random string of characters used to sign JWT tokens for basic auth.
