{{- if .Values.polly.enabled }}
{{- if and .Values.polly.queue.enabled .Values.polly.queue.autoscaling.enabled .Values.polly.queue.autoscaling.keda.enabled }}
apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "polly") }}-{{ .Values.polly.queue.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  scaleTargetRef:
    name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "polly") }}-{{ .Values.polly.queue.name }}
  minReplicaCount: {{ .Values.polly.queue.autoscaling.minReplicas | default 1 }}
  maxReplicaCount: {{ .Values.polly.queue.autoscaling.maxReplicas | default 10 }}
  pollingInterval: {{ .Values.polly.queue.autoscaling.keda.pollingInterval | default 30 }}
  cooldownPeriod: {{ .Values.polly.queue.autoscaling.keda.cooldownPeriod | default 300 }}
  advanced:
    horizontalPodAutoscalerConfig:
      behavior:
        scaleDown:
          stabilizationWindowSeconds: {{ .Values.polly.queue.autoscaling.keda.scaleDownStabilizationWindowSeconds | default 300 }}
  triggers:
    {{- if .Values.polly.queue.autoscaling.targetCPUUtilizationPercentage }}
    - type: cpu
      metricType: Utilization
      metadata:
        value: "{{ .Values.polly.queue.autoscaling.targetCPUUtilizationPercentage }}"
    {{- end }}
    {{- if .Values.polly.queue.autoscaling.targetMemoryUtilizationPercentage }}
    - type: memory
      metricType: Utilization
      metadata:
        value: "{{ .Values.polly.queue.autoscaling.targetMemoryUtilizationPercentage }}"
    {{- end }}
    - type: postgresql
      metadata:
        connectionFromEnv: "POSTGRES_URI"
        query: "SELECT COUNT(*) FROM run WHERE status = 'pending'"
        targetQueryValue: {{ .Values.polly.queue.numberOfJobsPerWorker | quote }}
        activationTargetQueryValue: {{ .Values.polly.queue.numberOfJobsPerWorker | quote }}
    {{- with .Values.polly.queue.autoscaling.keda.additionalTriggers }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- end }}
{{- end }}
