{{- if not .Values.connector.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.secretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "connector.fullname" . }}-{{ .Values.connector.name }}
  annotations:
    {{- include "connector.annotations" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.connector.apiKeySecretKey }}: {{ .Values.connector.apiKey | b64enc }}
{{- end }}
