{{- if .Values.connector.apiKey }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "connector.fullname" . }}-{{ .Values.connector.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "connector.labels" . | nindent 4 }}
  annotations:
    {{- include "connector.annotations" . | nindent 4 }}
type: Opaque
stringData:
  api-key: {{ .Values.connector.apiKey | quote }}
{{- end }}
