{{- $taskdb := .Values.smithdb.migration.taskdb.postgres -}}
{{- if and .Values.smithdb.enabled .Values.smithdb.langsmith.migration.enabled $taskdb.enabled (not $taskdb.external.enabled) $taskdb.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langsmith.smithdb.taskdbPostgresServiceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with $taskdb.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with $taskdb.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ $taskdb.statefulSet.automountServiceAccountToken }}
{{- end }}
