{{- $taskdb := .Values.smithdb.migration.taskdb.postgres -}}
{{- $existingSecretName := ternary $taskdb.external.existingSecretName $taskdb.auth.existingSecretName $taskdb.external.enabled -}}
{{- if and .Values.smithdb.enabled .Values.smithdb.langsmith.migration.enabled $taskdb.enabled (not $existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.smithdb.taskdbPostgresSecretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.smithdb.fullname" . }}-{{ $taskdb.name }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
type: Opaque
data:
  {{- if $taskdb.external.enabled }}
  {{ $taskdb.external.hostSecretKey }}: {{ $taskdb.external.host | b64enc }}
  {{ $taskdb.external.databaseSecretKey }}: {{ $taskdb.external.database | b64enc }}
  {{ $taskdb.external.usernameSecretKey }}: {{ $taskdb.external.username | b64enc }}
  {{ $taskdb.external.passwordSecretKey }}: {{ $taskdb.external.password | b64enc }}
  {{- else }}
  postgres_user: {{ $taskdb.auth.username | b64enc }}
  {{ $taskdb.auth.passwordSecretKey }}: {{ $taskdb.auth.password | b64enc }}
  postgres_db: {{ $taskdb.auth.database | b64enc }}
  {{- end }}
{{- end }}
