apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "missionControl.frontendDeploymentName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "missionControl.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
  {{- with (include "missionControl.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  replicas: {{ .Values.frontend.replicas }}
  selector:
    matchLabels:
      {{- include "missionControl.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: frontend
  template:
    metadata:
      labels:
        {{- include "missionControl.labels" . | nindent 8 }}
        app.kubernetes.io/component: frontend
      {{- with (include "missionControl.commonPodAnnotations" .) }}
      annotations:
        {{- . | nindent 8 }}
      {{- end }}
    spec:
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.frontend.podSecurityContext }}
      securityContext:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: frontend
          image: {{ include "missionControl.image" (dict "Values" .Values "Chart" .Chart "component" "frontendImage") }}
          imagePullPolicy: {{ .Values.images.frontendImage.pullPolicy }}
          ports:
            - containerPort: 3000
          {{- with .Values.frontend.securityContext }}
          securityContext:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.extraEnv }}
          env:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with .Values.frontend.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
