{{- if .Values.polly.enabled }}
{{- if not .Values.polly.redis.external.existingSecretName }}
{{- $componentName := include "langsmith.polly.redisComponentName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.agentFeatures.redisSecretName" (dict "root" . "product" "polly") }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.polly.redis.external.enabled }}
  redis_connection_url: {{ .Values.polly.redis.external.connectionUrl | b64enc }}
  {{- else }}
  redis_connection_url: {{ printf "redis://%s.%s.svc.%s:%v" $componentName (default .Release.Namespace .Values.namespace) .Values.clusterDomain (toString .Values.polly.redis.service.port) | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
