{{- if .Values.polly.enabled }}
{{- if and (not .Values.polly.redis.external.enabled) .Values.polly.redis.serviceAccount.create -}}
{{- $componentName := include "langsmith.polly.redisComponentName" . -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.polly.redis.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.polly.redis.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
