{{- if .Values.config.sandboxes.enabled }}
{{- $namespace := .Values.namespace | default .Release.Namespace }}
{{- $mountPodPatch := .Values.config.sandboxes.juicefs.csi.mountPodPatch }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "langsmith.sandboxes.juicefsCSIConfigMapName" . }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: config
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "langsmith.sandboxes.juicefsCSIAnnotations" . | nindent 4 }}
data:
  config.yaml: |-
    enableNodeSelector: false
    mountPodPatch:
{{- toYaml $mountPodPatch | nindent 4 }}
{{- end }}
