{{- if .Values.config.sandboxes.enabled }}
apiVersion: storage.k8s.io/v1
kind: CSIDriver
metadata:
  name: {{ include "langsmith.sandboxes.juicefsCSIDriverName" . }}
  labels:
    app.kubernetes.io/component: driver
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
  annotations:
    helm.sh/resource-policy: keep
    {{- include "langsmith.sandboxes.juicefsCSIAnnotations" . | nindent 4 }}
spec:
  attachRequired: false
  fsGroupPolicy: ReadWriteOnceWithFSType
  podInfoOnMount: true
  requiresRepublish: false
  seLinuxMount: false
  storageCapacity: false
  volumeLifecycleModes:
    - Persistent
{{- end }}
