{{- if .Values.config.sandboxes.enabled }}
{{- $namespace := .Values.namespace | default .Release.Namespace }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langsmith.sandboxes.juicefsCSIControllerServiceAccountName" . }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.sandboxes.juicefsCSIAnnotations" . | nindent 4 }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langsmith.sandboxes.juicefsCSINodeServiceAccountName" . }}
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: node
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.sandboxes.juicefsCSIAnnotations" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: juicefs-csi-external-provisioner-role
  labels:
    app.kubernetes.io/component: controller
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/status
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
      - csinodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: juicefs-csi-external-provisioner-role
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - pods/log
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
      - persistentvolumeclaims/status
    verbs:
      - get
      - list
      - watch
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ""
    resources:
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - apps
    resources:
      - daemonsets
      - replicasets
    verbs:
      - get
      - list
  - apiGroups:
      - coordination.k8s.io
    resources:
      - leases
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - watch
      - list
      - delete
      - update
      - create
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: juicefs-csi-external-node-service-role
  labels:
    app.kubernetes.io/component: node
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - watch
  - apiGroups:
      - ""
    resources:
      - nodes
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: juicefs-csi-external-node-service-role
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: node
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
      - create
      - update
      - delete
      - patch
      - watch
  - apiGroups:
      - ""
    resources:
      - pods/log
    verbs:
      - get
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
      - delete
  - apiGroups:
      - batch
    resources:
      - jobs
    verbs:
      - get
      - create
      - update
      - delete
      - patch
  - apiGroups:
      - ""
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - create
      - get
  - apiGroups:
      - ""
    resources:
      - configmaps
    verbs:
      - get
      - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: juicefs-csi-provisioner-binding
  labels:
    app.kubernetes.io/component: controller
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: juicefs-csi-external-provisioner-role
subjects:
  - kind: ServiceAccount
    name: {{ include "langsmith.sandboxes.juicefsCSIControllerServiceAccountName" . }}
    namespace: {{ $namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juicefs-csi-provisioner-binding
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: controller
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: juicefs-csi-external-provisioner-role
subjects:
  - kind: ServiceAccount
    name: {{ include "langsmith.sandboxes.juicefsCSIControllerServiceAccountName" . }}
    namespace: {{ $namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: juicefs-csi-node-service-binding
  labels:
    app.kubernetes.io/component: node
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: juicefs-csi-external-node-service-role
subjects:
  - kind: ServiceAccount
    name: {{ include "langsmith.sandboxes.juicefsCSINodeServiceAccountName" . }}
    namespace: {{ $namespace | quote }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: juicefs-csi-node-service-binding
  namespace: {{ $namespace | quote }}
  labels:
    app.kubernetes.io/component: node
    {{- include "langsmith.sandboxes.juicefsCSILabels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: juicefs-csi-external-node-service-role
subjects:
  - kind: ServiceAccount
    name: {{ include "langsmith.sandboxes.juicefsCSINodeServiceAccountName" . }}
    namespace: {{ $namespace | quote }}
{{- end }}
