{{- if .Values.insights.enabled }}
{{- if .Values.insights.postgres.pdb.enabled }}
{{- $componentSuffix := printf "%s-%s" .Values.insights.namePrefix .Values.insights.postgres.name -}}
{{- $componentPrefixMaxLen := int (sub 62 (len $componentSuffix)) -}}
{{- $componentPrefix := include "langsmith.fullname" . | trunc $componentPrefixMaxLen | trimSuffix "-" -}}
{{- $componentName := printf "%s-%s" $componentPrefix $componentSuffix -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $componentName }}
  {{- if .Values.insights.postgres.pdb.minAvailable }}
  minAvailable: {{ .Values.insights.postgres.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.insights.postgres.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.insights.postgres.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
