{{- if .Values.insights.enabled }}
{{- if .Values.insights.postgres.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "insights") }}-{{ .Values.insights.postgres.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "insights") }}-{{ .Values.insights.postgres.name }}
  {{- if .Values.insights.postgres.pdb.minAvailable }}
  minAvailable: {{ .Values.insights.postgres.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.insights.postgres.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.insights.postgres.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
