{{- if .Values.insights.enabled }}
{{- if not .Values.insights.postgres.external.existingSecretName }}
{{- $componentSuffix := printf "%s-%s" .Values.insights.namePrefix .Values.insights.postgres.name -}}
{{- $componentPrefixMaxLen := int (sub 62 (len $componentSuffix)) -}}
{{- $componentPrefix := include "langsmith.fullname" . | trunc $componentPrefixMaxLen | trimSuffix "-" -}}
{{- $componentName := printf "%s-%s" $componentPrefix $componentSuffix -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.agentFeatures.postgresSecretName" (dict "root" . "product" "insights") }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.insights.postgres.external.enabled }}
  {{- if .Values.insights.postgres.external.connectionUrl }}
  postgres_connection_url: {{ .Values.insights.postgres.external.connectionUrl | b64enc }}
  {{- else }}
  postgres_connection_url: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" .Values.insights.postgres.external.user .Values.insights.postgres.external.password .Values.insights.postgres.external.host (toString .Values.insights.postgres.external.port) .Values.insights.postgres.external.database | b64enc }}
  {{- end }}
  {{- else }}
  postgres_user: {{ .Values.insights.postgres.external.user | b64enc }}
  postgres_password: {{ .Values.insights.postgres.external.password | b64enc }}
  postgres_db: {{ .Values.insights.postgres.external.database | b64enc }}
  postgres_connection_url: {{ printf "postgres://%s:%s@%s.%s.svc.%s:%s/%s?sslmode=disable" .Values.insights.postgres.external.user .Values.insights.postgres.external.password $componentName (default .Release.Namespace .Values.namespace) .Values.clusterDomain (toString .Values.insights.postgres.service.port) .Values.insights.postgres.external.database | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
