{{- if .Values.insights.enabled }}
{{- if and (not .Values.insights.postgres.external.enabled) .Values.insights.postgres.serviceAccount.create -}}
{{- $componentSuffix := printf "%s-%s" .Values.insights.namePrefix .Values.insights.postgres.name -}}
{{- $componentPrefixMaxLen := int (sub 62 (len $componentSuffix)) -}}
{{- $componentPrefix := include "langsmith.fullname" . | trunc $componentPrefixMaxLen | trimSuffix "-" -}}
{{- $componentName := printf "%s-%s" $componentPrefix $componentSuffix -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.insights.postgres.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.insights.postgres.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
