{{- if .Values.fleet.enabled }}
{{- $envVars := concat .Values.commonEnv (include "langsmith.commonEnv" . | fromYamlArray) (include "langsmith.agentFeatures.deploymentEnv" (dict "root" . "product" "fleet" "component" "apiServer") | fromYamlArray) (include "langsmith.fleet.extraEnv" . | fromYamlArray) .Values.fleet.apiServer.deployment.extraEnv -}}
{{- include "langsmith.detectDuplicates" $envVars -}}
{{- $volumes := concat .Values.commonVolumes .Values.fleet.apiServer.deployment.volumes (include "langsmith.tlsVolumes" . | fromYamlArray) -}}
{{- $volumeMounts := concat .Values.commonVolumeMounts .Values.fleet.apiServer.deployment.volumeMounts (include "langsmith.tlsVolumeMounts" . | fromYamlArray) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") }}-{{ .Values.fleet.apiServer.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.fleet.apiServer.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.fleet.apiServer.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.fleet.apiServer.autoscaling.enabled }}
  replicas: {{ .Values.fleet.apiServer.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") }}-{{ .Values.fleet.apiServer.name }}
  template:
    metadata:
      annotations:
      {{- include "langsmith.commonPodAnnotations" . | nindent 8 }}
      {{- with .Values.fleet.apiServer.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.fleet.apiServer.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") }}-{{ .Values.fleet.apiServer.name }}
    spec:
      serviceAccountName: {{ include "fleetApiServer.serviceAccountName" . }}
      {{- include "langsmith.dnsConfig" . | nindent 6 }}
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.fleet.apiServer.deployment.priorityClassName }}
      priorityClassName: {{ .Values.fleet.apiServer.deployment.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.fleet.apiServer.deployment.terminationGracePeriodSeconds }}
      securityContext:
        {{- merge .Values.fleet.apiServer.deployment.podSecurityContext (.Values.commonPodSecurityContext | default dict) | toYaml | nindent 8 }}
      {{- $initContainers := concat (.Values.commonInitContainers | default list) (.Values.fleet.apiServer.deployment.initContainers | default list) }}
      {{- with $initContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.fleet.apiServer.name }}
          env:
            {{- with $envVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "langsmith.fullname" . }}-config
            {{- with .Values.fleet.apiServer.deployment.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "langsmith.image" (dict "Values" .Values "Chart" .Chart "component" "agentBuilderImage") | quote }}
          imagePullPolicy: {{ .Values.images.agentBuilderImage.pullPolicy }}
          ports:
            - name: api-server
              containerPort: {{ .Values.fleet.apiServer.containerPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.fleet.apiServer.deployment.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.fleet.apiServer.deployment.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.fleet.apiServer.deployment.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.fleet.apiServer.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.fleet.apiServer.deployment.securityContext | nindent 12 }}
          {{- with .Values.fleet.apiServer.deployment.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.fleet.apiServer.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.fleet.apiServer.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fleet.apiServer.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.fleet.apiServer.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
