{{- if .Values.fleet.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") }}-{{ .Values.fleet.apiServer.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.fleet.apiServer.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.fleet.apiServer.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.fleet.apiServer.service.type }}
  ports:
    - name: http
      port: {{ .Values.fleet.apiServer.service.httpPort }}
      targetPort: api-server
      protocol: TCP
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") }}-{{ .Values.fleet.apiServer.name }}
{{- end }}
