{{- if and .Values.sandboxes.enabled (eq .Values.sandboxes.deploymentMode "sameCluster") (not .Values.sandboxes.juicefs.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.sandboxes.juicefsConfigSecretName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
    {{- include "langsmith.annotations" . | nindent 4 }}
type: Opaque
stringData:
{{ include "langsmith.sandboxes.juicefsConfigSecretData" . | indent 2 }}
{{- end }}
