{{- if and .Values.config.sandboxes.enabled .Values.config.sandboxes.createNamespace }}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ include "langsmith.sandboxes.namespace" . }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
{{- end }}
