{{- if and .Values.config.sandboxes.enabled .Values.config.sandboxes.smithboxControl.enabled (not .Values.redis.external.cluster.enabled) (not .Values.config.sandboxes.smithboxControl.redis.existingSecretName) (not .Values.redis.external.existingSecretName) (not .Values.redis.disableSecretCreation) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.sandboxes.smithboxControlRedisSecretName" . }}
  namespace: {{ include "langsmith.sandboxes.namespace" . }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    "argocd.argoproj.io/sync-wave": "-2"
    {{- include "langsmith.annotations" . | nindent 4 }}
type: Opaque
stringData:
  {{ include "langsmith.sandboxes.smithboxControlRedisConnectionUrlSecretKey" . }}: {{ include "langsmith.sandboxes.redisConnectionUrl" . | quote }}
{{- end }}
