{{- if .Values.config.sandboxes.enabled }}
{{- $namespace := .Values.namespace | default .Release.Namespace }}
{{- if .Values.config.sandboxes.sandboxHost.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "langsmith.sandboxes.sandboxHostServiceAccountName" . }}
  namespace: {{ $namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.config.sandboxes.sandboxHost.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.config.sandboxes.sandboxHost.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: {{ .Values.config.sandboxes.sandboxHost.serviceAccount.automountServiceAccountToken }}
---
{{- end }}
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: sandbox-host-lease
  namespace: {{ $namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
rules:
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["create", "get", "list", "watch", "update", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: sandbox-host-lease
  namespace: {{ $namespace }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "langsmith.sandboxes.sandboxHostServiceAccountName" . }}
    namespace: {{ $namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: sandbox-host-lease
{{- end }}
