apiVersion: v1
kind: Service
metadata:
  name: {{ include "langsmith-mission-control.fullname" . }}-backend
spec:
  type: {{ .Values.backendService.type }}
  ports:
    - port: {{ .Values.backendService.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    app: {{ include "langsmith-mission-control.name" . }}-backend
