{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "langsmith-mission-control.fullname" . }}
  namespace: {{ .Release.Namespace }}
spec:
  rules:
    - host: {{ .Values.ingress.host | quote }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: {{ include "langsmith-mission-control.fullname" . }}-frontend
                port:
                  number: {{ .Values.frontendService.port }}
{{- end }}
