{{- if .Values.polly.enabled }}
{{- if not .Values.polly.postgres.external.existingSecretName }}
{{- $componentName := include "langsmith.polly.postgresComponentName" . -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.agentFeatures.postgresSecretName" (dict "root" . "product" "polly") }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.polly.postgres.external.enabled }}
  {{- if .Values.polly.postgres.external.connectionUrl }}
  postgres_connection_url: {{ .Values.polly.postgres.external.connectionUrl | b64enc }}
  {{- else }}
  postgres_connection_url: {{ printf "postgres://%s:%s@%s:%s/%s?sslmode=disable" .Values.polly.postgres.external.user .Values.polly.postgres.external.password .Values.polly.postgres.external.host (toString .Values.polly.postgres.external.port) .Values.polly.postgres.external.database | b64enc }}
  {{- end }}
  {{- else }}
  postgres_user: {{ .Values.polly.postgres.external.user | b64enc }}
  postgres_password: {{ .Values.polly.postgres.external.password | b64enc }}
  postgres_db: {{ .Values.polly.postgres.external.database | b64enc }}
  postgres_connection_url: {{ printf "postgres://%s:%s@%s.%s.svc.%s:%s/%s?sslmode=disable" .Values.polly.postgres.external.user .Values.polly.postgres.external.password $componentName (default .Release.Namespace .Values.namespace) .Values.clusterDomain (toString .Values.polly.postgres.service.port) .Values.polly.postgres.external.database | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
