{{- if or .Values.insights.enabled .Values.engine.enabled }}
{{- if .Values.engineInsightsAgent.redis.pdb.enabled }}
{{- $componentName := include "langsmith.agentFeatures.componentName" (dict "root" . "product" "engineInsightsAgent" "component" "redis") -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $componentName }}
  {{- if hasKey .Values.engineInsightsAgent.redis.pdb "minAvailable" }}
  minAvailable: {{ .Values.engineInsightsAgent.redis.pdb.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.engineInsightsAgent.redis.pdb "maxUnavailable" }}
  maxUnavailable: {{ .Values.engineInsightsAgent.redis.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
