{{- if .Values.insights.enabled }}
{{- if not .Values.insights.redis.external.existingSecretName }}
{{- $componentName := include "langsmith.agentFeatures.componentName" (dict "root" . "product" "insights" "component" "redis") -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.agentFeatures.redisSecretName" (dict "root" . "product" "insights") }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.insights.redis.external.enabled }}
  redis_connection_url: {{ .Values.insights.redis.external.connectionUrl | b64enc }}
  {{- else }}
  redis_connection_url: {{ printf "redis://%s.%s.svc.%s:%v" $componentName (default .Release.Namespace .Values.namespace) .Values.clusterDomain (toString .Values.insights.redis.service.port) | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
