{{- if .Values.insights.enabled }}
{{- if not .Values.insights.redis.external.enabled }}
{{- $componentName := include "langsmith.insights.redisComponentName" . -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.insights.redis.service.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.insights.redis.service.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.insights.redis.service.type }}
  ports:
    - name: redis
      port: {{ .Values.insights.redis.service.port }}
      targetPort: redis
      protocol: TCP
  selector:
    {{- include "langsmith.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: {{ $componentName }}
  {{- end }}
{{- end }}
