{{- if .Values.insights.enabled }}
{{- if .Values.insights.queue.enabled -}}
{{- $envVars := concat .Values.commonEnv (include "langsmith.commonEnv" . | fromYamlArray) (include "langsmith.agentFeatures.deploymentEnv" (dict "root" . "product" "insights" "component" "queue") | fromYamlArray) (include "langsmith.insights.extraEnv" . | fromYamlArray) .Values.insights.queue.deployment.extraEnv -}}
{{- include "langsmith.detectDuplicates" $envVars -}}
{{- $volumes := concat .Values.commonVolumes .Values.insights.queue.deployment.volumes (include "langsmith.tlsVolumes" . | fromYamlArray) -}}
{{- $volumeMounts := concat .Values.commonVolumeMounts .Values.insights.queue.deployment.volumeMounts (include "langsmith.tlsVolumeMounts" . | fromYamlArray) -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "insights") }}-{{ .Values.insights.queue.name }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.insights.queue.deployment.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.insights.queue.deployment.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  {{- if not .Values.insights.queue.autoscaling.enabled }}
  replicas: {{ .Values.insights.queue.deployment.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "insights") }}-{{ .Values.insights.queue.name }}
  template:
    metadata:
      annotations:
      {{- include "langsmith.commonPodAnnotations" . | nindent 8 }}
      {{- with .Values.insights.queue.deployment.annotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- with .Values.insights.queue.deployment.labels }}
            {{- toYaml . | nindent 8 }}
        {{- end }}
        {{- include "langsmith.labels" . | nindent 8 }}
        app.kubernetes.io/component: {{ include "langsmith.agentFeatures.fullname" (dict "root" . "product" "insights") }}-{{ .Values.insights.queue.name }}
    spec:
      serviceAccountName: {{ include "insightsQueue.serviceAccountName" . }}
      {{- include "langsmith.dnsConfig" . | nindent 6 }}
      {{- with .Values.images.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if .Values.insights.queue.deployment.priorityClassName }}
      priorityClassName: {{ .Values.insights.queue.deployment.priorityClassName }}
      {{- end }}
      terminationGracePeriodSeconds: {{ .Values.insights.queue.deployment.terminationGracePeriodSeconds }}
      securityContext:
        {{- merge .Values.insights.queue.deployment.podSecurityContext (.Values.commonPodSecurityContext | default dict) | toYaml | nindent 8 }}
      {{- with .Values.commonInitContainers }}
      initContainers:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Values.insights.queue.name }}
          command:
            - "/storage/queue_entrypoint.sh"
          env:
            {{- with $envVars }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          envFrom:
            - configMapRef:
                name: {{ include "langsmith.fullname" . }}-config
            {{- with .Values.insights.queue.deployment.envFrom }}
              {{- toYaml . | nindent 12 }}
            {{- end }}
          image: {{ include "langsmith.image" (dict "Values" .Values "Chart" .Chart "component" "insightsAgentImage") | quote }}
          imagePullPolicy: {{ .Values.images.insightsAgentImage.pullPolicy }}
          ports:
            - name: queue
              containerPort: {{ .Values.insights.queue.containerPort }}
              protocol: TCP
          startupProbe:
            {{- toYaml .Values.insights.queue.deployment.startupProbe | nindent 12 }}
          readinessProbe:
            {{- toYaml .Values.insights.queue.deployment.readinessProbe | nindent 12 }}
          livenessProbe:
            {{- toYaml .Values.insights.queue.deployment.livenessProbe | nindent 12 }}
          resources:
            {{- toYaml .Values.insights.queue.deployment.resources | nindent 12 }}
          securityContext:
            {{- toYaml .Values.insights.queue.deployment.securityContext | nindent 12 }}
          {{- with .Values.insights.queue.deployment.lifecycle }}
          lifecycle:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- with $volumeMounts }}
          volumeMounts:
              {{- toYaml . | nindent 12 }}
          {{- end }}
        {{- with .Values.insights.queue.deployment.sidecars }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      {{- with .Values.insights.queue.deployment.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.insights.queue.deployment.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.insights.queue.deployment.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $volumes }}
      volumes:
          {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end}}
{{- end }}
