{{- if or .Values.observability.logs.enabled .Values.observability.metrics.enabled .Values.observability.traces.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      otlp:
        protocols:
          grpc:
            endpoint: ${env:MY_POD_IP}:4317
          http:
            endpoint: ${env:MY_POD_IP}:4318
      filelog:
        exclude: []
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        retry_on_failure:
          enabled: true
        start_at: end
    
    processors:
      batch: {}
      memory_limiter:
        check_interval: 5s
        limit_percentage: 80
        spike_limit_percentage: 25
      filter:
        error_mode: ignore
        logs:
          log_record:
          - resource.attributes["k8s.namespace.name"] != "romain"
          - resource.attributes["k8s.app.name"] != "{{ .Values.global.langsmithNamespace }}"
      k8sattributes:
        extract:
          labels:
          - from: pod
            key: app.kubernetes.io/name
            tag_name: k8s.app.name
          metadata:
          - k8s.namespace.name
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

    exporters:
      {{- if eq .Values.observability.logs.backend "local" }}
      otlphttp/logs:
        endpoint: http://langsmith-observability-loki-gateway.romain-observability.svc.cluster.local:80/otlp
        tls:
          insecure: true
      {{- end }}
    
    service:
      extensions:
        - health_check
      pipelines:
        {{- if .Values.observability.logs.enabled }}
        logs:
          receivers:
            - otlp
            - filelog
          processors:
            - batch
            - filter
            - k8sattributes
            - memory_limiter
          exporters:
            - otlphttp/logs
        {{- end }}
{{ end }}