{{- if or .Values.observability.logs.enabled (or .Values.observability.metrics.enabled .Values.observability.traces.enabled) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      {{- if .Values.observability.logs.enabled }}
      filelog:
        exclude: []
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        retry_on_failure:
          enabled: true
        start_at: end
      {{- end }}
      {{- if .Values.observability.metrics.enabled }}
      prometheus:
        config:
          scrape_configs:
            {{- if .Values.observability.metrics.postgres.enabled }}
            - job_name: 'postgres-exporter'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-postgresexporter.romain-observability.svc.cluster.local:80']
            {{- end }}
            {{- if .Values.observability.metrics.redis.enabled }}
            - job_name: 'redis-exporter'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-redisexporter.romain-observability.svc.cluster.local:9121']
            {{- end }}
            {{- if .Values.observability.metrics.kubeStateMetrics.enabled }}
            - job_name: 'kube_state_metrics'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-kube-state-metrics.romain-observability.svc.cluster.local:8080']
            {{- end }}
            {{- if .Values.observability.metrics.clickhouse.enabled }}
            - job_name: 'clickhouse'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-clickhouse.romain.svc.cluster.local:9363']
            {{- end }}
            {{- if .Values.observability.metrics.langsmith.enabled }}
            - job_name: 'langsmith_services'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-backend.romain.svc.cluster.local:1984', 'langsmith-playground.romain.svc.cluster.local:1988']
            {{- end }}
      {{- end }}
      {{- if .Values.observability.metrics.hostMetrics.enabled }}
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
          load:
          network:
          paging:
          system:
      hostmetrics/disk:
        collection_interval: 1m
        scrapers:
          disk:
          filesystem:
      {{- end }}
      {{- if .Values.observability.traces.enabled }}
      otlp:
        protocols:
          grpc: 
            endpoint: 0.0.0.0:4317
          http: 
            endpoint: 0.0.0.0:4318
      {{- end}}
    processors:
      batch: {}
      memory_limiter:
        check_interval: 1m
        limit_percentage: 75
        spike_limit_percentage: 25
      filter:
        error_mode: ignore
        logs:
          log_record:
          - 'resource.attributes["k8s.namespace.name"] != "{{ .Values.global.langsmithNamespace }}"'
          - 'resource.attributes["k8s.app.name"] != "langsmith"'
      k8sattributes:
        extract:
          labels:
          - from: pod
            key: app.kubernetes.io/name
            tag_name: k8s.app.name
          metadata:
          - k8s.namespace.name
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection
      
    connectors:
      datadog/connector:

    exporters:
      debug:
        verbosity: detailed
      {{- if .Values.observability.logs.local_backend }}
      otlphttp/logs:
        endpoint: http://langsmith-observability-loki-gateway.romain-observability.svc.cluster.local:80/otlp
        tls:
          insecure: true
      {{- end }}
      {{- if .Values.observability.metrics.local_backend }}
      otlphttp/metrics:
        endpoint: http://langsmith-observability-mimir-nginx.romain-observability.svc.cluster.local:80/otlp
        tls:
          insecure: true
      {{- end }}
      {{- if .Values.observability.traces.local_backend }}
      otlp/traces:
        endpoint: langsmith-observability-tempo-distributor-discovery.romain-observability.svc.cluster.local:4317
        tls:
          insecure: true
      {{- end }}
      datadog/exporter:
        api:
          site: us5.datadoghq.com
          key: fc092e5ae3f0c7c476b2c5071442eeee
    
    service:
      telemetry:
        logs:
          level: "debug"
      extensions:
        - health_check
      pipelines:
        {{- if .Values.observability.logs.enabled }}
        logs/langsmith_backend:
          receivers:
            - filelog
          processors:
            - k8sattributes
            - filter
            - batch
          exporters:
            - debug
            {{- if .Values.observability.logs.local_backend }}
            - otlphttp/logs
            {{- end }}
        {{- end }}
        {{- if .Values.observability.metrics.enabled }}
        metrics/langsmith_backend:
          receivers:
            - prometheus
            {{- if .Values.observability.metrics.hostMetrics.enabled }}
            - hostmetrics
            - hostmetrics/disk
            {{- end }}
          processors:
            - batch
          exporters:
            - debug
            {{- if .Values.observability.metrics.local_backend }}
            - otlphttp/metrics
            {{- end }}
        {{- end }}
        {{- if .Values.observability.traces.enabled }}
        traces/langsmith_backend:
          receivers:
            - otlp
          processors:
            - memory_limiter
            - batch
          exporters:
            - datadog/exporter
        {{- end }}
{{- end }}