{{- if or .Values.observability.logs.enabled .Values.observability.metrics.enabled .Values.observability.traces.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "opentelemetry-collector.fullname" . }}-agent
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    extensions:
      health_check:
        endpoint: ${env:MY_POD_IP}:13133

    receivers:
      {{- if .Values.observability.logs.enabled }}
      filelog:
        exclude: []
        include:
        - /var/log/pods/*/*/*.log
        include_file_name: false
        include_file_path: true
        operators:
        - id: container-parser
          max_log_size: 102400
          type: container
        retry_on_failure:
          enabled: true
        start_at: end
      {{- end }}
      {{- if .Values.observability.metrics.enabled }}
      prometheus:
        config:
          scrape_configs:
            - job_name: 'postgres-exporter'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-postgresexporter.romain-observability.svc.cluster.local:80']
            - job_name: 'redis-exporter'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-redisexporter.romain-observability.svc.cluster.local:9121']
            - job_name: 'kube_state_metrics'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-observability-kube-state-metrics.romain-observability.svc.cluster.local:8080']
            - job_name: 'clickhouse'
              metrics_path: /metrics
              static_configs:
                - targets: ['langsmith-clickhouse.romain.svc.cluster.local:9363']
      {{- end }}
      {{- if .Values.observability.metrics.hostMetrics.enabled }}
      hostmetrics:
        collection_interval: 30s
        scrapers:
          cpu:
          memory:
          load:
          network:
          paging:
          system:
      hostmetrics/disk:
        collection_interval: 1m
        scrapers:
          disk:
          filesystem:
      {{- end }}

    processors:
      batch: {}
      filter:
        error_mode: ignore
        logs:
          log_record:
          - 'resource.attributes["k8s.namespace.name"] != "{{ .Values.global.langsmithNamespace }}"'
          - 'resource.attributes["k8s.app.name"] != "langsmith"'
      k8sattributes:
        extract:
          labels:
          - from: pod
            key: app.kubernetes.io/name
            tag_name: k8s.app.name
          metadata:
          - k8s.namespace.name
        filter:
          node_from_env_var: K8S_NODE_NAME
        passthrough: false
        pod_association:
        - sources:
          - from: resource_attribute
            name: k8s.pod.ip
        - sources:
          - from: resource_attribute
            name: k8s.pod.uid
        - sources:
          - from: connection

    exporters:
      {{- if eq .Values.observability.logs.backend "local" }}
      otlphttp/logs:
        endpoint: http://langsmith-observability-loki-gateway.romain-observability.svc.cluster.local:80/otlp
        tls:
          insecure: true
      {{- end }}
      {{- if eq .Values.observability.metrics.backend "local" }}
      otlphttp/metrics:
        endpoint: http://langsmith-observability-mimir-nginx.romain-observability.svc.cluster.local:80/otlp
        tls:
          insecure: true
      {{- end }}
    
    service:
      extensions:
        - health_check
      pipelines:
        {{- if .Values.observability.logs.enabled }}
        logs/langsmith_backend:
          receivers:
            - filelog
          processors:
            - k8sattributes
            - filter
            - batch
          exporters:
            - otlphttp/logs
        {{- end }}
        {{- if .Values.observability.metrics.enabled }}
        metrics/langsmith_backend:
          receivers:
            - prometheus
            {{- if .Values.observability.metrics.hostMetrics.enabled }}
            - hostmetrics
            - hostmetrics/disk
            {{- end }}
          processors:
            - batch
          exporters:
            - otlphttp/metrics
        {{- end }}
{{ end }}