global:
  envOverrides: []
  langsmithNamespace: romain

observability:
  grafana:
    enabled: true
  logs:
    enabled: false
    local_backend: false # local or external
    local_persistence: false # local or s3
    
  metrics:
    enabled: false
    local_backend: false # local or external
    local_persistence: false # local or s3
    
    postgres:
      enabled: false
    redis:
      enabled: false
    langsmith:
      enabled: false
    kubeStateMetrics:
      enabled: false 
    hostMetrics:
      enabled: false
    clickhouse:
      mode: "cluster" # cluster or external
      enabled: false

  traces:
    enabled: true
    local_backend: true # local or external
    local_persistence: false # local or s3

minio:
  enabled: true
  mode: standalone
  replicas: 1
  persistence:
    enabled: true
    size: 10Gi
  readinessProbe:
    enabled: false
  auth:
    rootUser: admin
    rootPassword: admin_password
  defaultBuckets: "loki-chunks, loki-ruler, loki-admin, mimir-blocks, mimir-ruler, mimir-alertmanager, tempo"

otelcollector:
  name: langsmith-observability-otel-collector
  image:
    registry: otel/opentelemetry-collector-k8s
    tag: "0.127.0"
  serviceAccount:
    annotations: {}
    labels: {}
  clusterRoleBinding:
    annotations: {}
  clusterRole:
    annotations: {}
    rules: []
  daemonset:
    annotations: {}
  pod:
    annotations: {}

grafana:
  datasources:
    datasources.yaml:
      apiVersion: 1
      # -- Datasources linked to the Grafana instance. Override if you disable any components.
      datasources:
        # https://grafana.com/docs/grafana/latest/datasources/loki/#provision-the-loki-data-source
        - name: Loki
          uid: loki
          type: loki
          url: http://{{ .Release.Name }}-loki-gateway
          isDefault: false
        # https://grafana.com/docs/grafana/latest/datasources/prometheus/#provision-the-data-source
        - name: Mimir
          uid: prom
          type: prometheus
          url: http://{{ .Release.Name }}-mimir-nginx/prometheus
          isDefault: false
        - name: Tempo
          uid: tempo
          type: tempo
          url: http://{{ .Release.Name }}-tempo-query-frontend-discovery:3200
          isDefault: false
          jsonData:
            tracesToLogsV2:
              datasourceUid: loki
            lokiSearch:
              datasourceUid: loki
            tracesToMetrics:
              datasourceUid: prom
            serviceMap:
              datasourceUid: prom

logs_backend:
  loki:
    auth_enabled: false
    schemaConfig:
      configs:
        - from: "2024-04-01"
          store: tsdb
          object_store: s3
          schema: v13
          index:
            prefix: loki_index_
            period: 24h
    
    storage_config:
      aws:
        region: us-east-1
        bucketnames: loki-chunks
        s3forcepathstyle: true

    storage:
      type: s3
      bucketNames:
        chunks: loki-chunks
        ruler: loki-ruler
        admin: loki-admin
      s3:
        endpoint: langsmith-observability-minio.romain-observability.svc.cluster.local:9000
        region: us-east-1
        secretAccessKey: admin_password
        accessKeyId: admin
        insecure: true
        s3ForcePathStyle: true

    ingester:
      chunk_encoding: snappy
    querier:
      # Default is 4, if you have enough memory and CPU you can increase, reduce if OOMing
      max_concurrent: 4
    pattern_ingester:
      enabled: true
    limits_config:
      allow_structured_metadata: true
      volume_enabled: true

  deploymentMode: Distributed

  ingester:
    replicas: 3 # To ensure data durability with replication
    zoneAwareReplication:
      enabled: false
  querier:
    replicas: 3 # Improve query performance via parallelism
    maxUnavailable: 2
  queryFrontend:
    replicas: 2
    maxUnavailable: 1
  queryScheduler:
    replicas: 2
  distributor:
    replicas: 3 
    maxUnavailable: 2
  compactor:
    replicas: 1
  indexGateway:
    replicas: 2
    maxUnavailable: 1

  bloomPlanner:
    replicas: 0
  bloomBuilder:
    replicas: 0
  bloomGateway:
    replicas: 0

  backend:
    replicas: 0
  read:
    replicas: 0
  write:
    replicas: 0

  singleBinary:
    replicas: 0

metrics_backend:
  minio:
    enabled: false
  mimir:
    structuredConfig:
      common:
        storage:
          backend: s3
          s3:
            endpoint: langsmith-observability-minio.romain-observability.svc.cluster.local:9000
            region: us-east-1
            secret_access_key: admin_password
            access_key_id: admin
            insecure: true

      blocks_storage:
        s3:
          bucket_name: mimir-blocks

      alertmanager_storage:
        s3:
          bucket_name: mimir-alertmanager

      ruler_storage:
        s3:
          bucket_name: mimir-ruler


traces_backend:
  storage:
    trace:
      backend: s3
      s3:
        access_key: admin
        secret_key: admin_password
        bucket: tempo
        endpoint: langsmith-observability-minio.romain-observability.svc.cluster.local:9000
        insecure: true
  # Specifies which trace protocols to accept by the gateway.
  traces:
    otlp:
      grpc:
        enabled: true
      http:
        enabled: true
    zipkin:
      enabled: false
    jaeger:
      thriftHttp:
        enabled: false
    opencensus:
      enabled: false
postgresexporter:
  config:
    datasource:
      host: langsmith-postgres.romain.svc.cluster.local
      port: "5432"
      user: postgres
      password: postgres
      database: ''
  serviceAccount:
    name: langsmith-observability-postgres-exporter

redisexporter:
  redisAddress: "redis://langsmith-redis.romain.svc.cluster.local:6379"
  serviceAccount:
    name: langsmith-observability-redis-exporter