{{- if .Values.fleet.enabled }}
{{- if .Values.fleet.postgres.pdb.enabled }}
{{- $componentName := include "langsmith.fleet.postgresComponentName" . -}}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "langsmith.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ $componentName }}
  {{- if hasKey .Values.fleet.postgres.pdb "minAvailable" }}
  minAvailable: {{ .Values.fleet.postgres.pdb.minAvailable }}
  {{- end }}
  {{- if hasKey .Values.fleet.postgres.pdb "maxUnavailable" }}
  maxUnavailable: {{ .Values.fleet.postgres.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
{{- end }}
