{{- if .Values.fleet.enabled }}
{{- if and (not .Values.fleet.postgres.external.enabled) .Values.fleet.postgres.serviceAccount.create -}}
{{- $componentName := include "langsmith.agentFeatures.componentName" (dict "root" . "product" "fleet" "component" "postgres") -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $componentName }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
    {{- with .Values.fleet.postgres.serviceAccount.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
    {{- with .Values.fleet.postgres.serviceAccount.annotations }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
automountServiceAccountToken: true
{{- end }}
{{- end }}
