{{- $defaultCheckpointerBackend := include "langGraphCloud.defaultCheckpointerBackend" . -}}
{{- if and (eq $defaultCheckpointerBackend "mongo") .Values.mongo.internal.enabled .Values.mongo.internal.pdb.enabled }}
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "langGraphCloud.mongoServiceName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langGraphCloud.labels" . | nindent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "langGraphCloud.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: {{ include "langGraphCloud.mongoServiceName" . }}
  {{- if .Values.mongo.internal.pdb.minAvailable }}
  minAvailable: {{ .Values.mongo.internal.pdb.minAvailable }}
  {{- end }}
  {{- if .Values.mongo.internal.pdb.maxUnavailable }}
  maxUnavailable: {{ .Values.mongo.internal.pdb.maxUnavailable }}
  {{- end }}
{{- end }}
