{{- $defaultCheckpointerBackend := include "langGraphCloud.defaultCheckpointerBackend" . -}}
{{- if and (eq $defaultCheckpointerBackend "mongo") (not .Values.checkpointer.mongo.external.existingSecretName) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langGraphCloud.mongoSecretsName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langGraphCloud.labels" . | nindent 4 }}
  annotations:
    {{- include "langGraphCloud.annotations" . | nindent 4 }}
data:
  {{ .Values.checkpointer.mongo.external.connectionUrlSecretKey }}: {{ .Values.checkpointer.mongo.external.connectionUrl | b64enc | quote }}
{{- end }}
