{{- $useExistingSecret := and .Values.mongo.external.enabled .Values.mongo.external.existingSecretName -}}
{{- if and .Values.mongo.enabled (not $useExistingSecret) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langGraphCloud.mongoSecretsName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langGraphCloud.labels" . | nindent 4 }}
  annotations:
    {{- include "langGraphCloud.annotations" . | nindent 4 }}
data:
  mongodb_connection_url: {{ include "langGraphCloud.mongoConnectionUrl" . | b64enc | quote }}
{{- end }}
