{{- if (dig "rbac" "create" true .Values.backend) }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "missionControl.fullname" . }}
  labels:
    {{- include "missionControl.labels" . | nindent 4 }}
  {{- with (include "missionControl.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
subjects:
  - kind: ServiceAccount
    name: {{ include "missionControl.serviceAccountName" . }}
    namespace: {{ .Values.namespace | default .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "missionControl.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
