apiVersion: v1
kind: Service
metadata:
  name: {{ include "missionControl.backendWorkloadName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "missionControl.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with (include "missionControl.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.backend.service.type }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8000
      protocol: TCP
  selector:
    {{- include "missionControl.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: backend
