{{- if .Values.backend.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "missionControl.serviceAccountName" . }}
  namespace: {{ .Values.namespace | default .Release.Namespace }}
  labels:
    {{- include "missionControl.labels" . | nindent 4 }}
    app.kubernetes.io/component: backend
  {{- with (include "missionControl.annotations" .) }}
  annotations:
    {{- . | nindent 4 }}
  {{- end }}
{{- end }}
