{{- if .Values.fleet.enabled }}
{{- if not .Values.fleet.redis.external.existingSecretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "langsmith.agentFeatures.redisSecretName" (dict "root" . "product" "fleet") }}
  namespace: {{ .Values.namespace | default .Release.Namespace | quote }}
  labels:
    {{- include "langsmith.labels" . | nindent 4 }}
  annotations:
    {{- include "langsmith.annotations" . | nindent 4 }}
data:
  {{- if .Values.fleet.redis.external.enabled }}
    redis_connection_url: {{ .Values.fleet.redis.external.connectionUrl | b64enc }}
  {{- else }}
    redis_connection_url: {{ printf "redis://%s-%s.%s.svc.%s:%v" (include "langsmith.agentFeatures.fullname" (dict "root" . "product" "fleet") ) .Values.fleet.redis.name (default .Release.Namespace .Values.namespace) .Values.clusterDomain .Values.fleet.redis.containerPort | b64enc }}
  {{- end}}
{{- end }}
{{- end }}
