{{/*
Expand the name of the chart.
*/}}
{{- define "missionControl.name" -}}
{{- default .Chart.Name .Values.nameOverride | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Create a default fully qualified app name.
We truncate at 63 chars because some Kubernetes name fields are limited to this (by the DNS naming spec).
If release name contains chart name it will be used as a full name.
*/}}
{{- define "missionControl.fullname" -}}
{{- if .Values.fullnameOverride }}
{{- .Values.fullnameOverride | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- $name := default .Chart.Name .Values.nameOverride }}
{{- if contains $name .Release.Name }}
{{- .Release.Name | trunc 63 | trimSuffix "-" }}
{{- else }}
{{- printf "%s-%s" .Release.Name $name | trunc 63 | trimSuffix "-" }}
{{- end }}
{{- end }}
{{- end }}

{{/*
Create chart name and version as used by the chart label.
*/}}
{{- define "missionControl.chart" -}}
{{- printf "%s-%s" .Chart.Name .Chart.Version | replace "+" "_" | trunc 63 | trimSuffix "-" }}
{{- end }}

{{/*
Selector labels
*/}}
{{- define "missionControl.selectorLabels" -}}
app.kubernetes.io/name: {{ include "missionControl.name" . }}
app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}

{{/*
Common labels
*/}}
{{- define "missionControl.labels" -}}
{{- if .Values.commonLabels }}
{{ toYaml .Values.commonLabels }}
{{- end }}
helm.sh/chart: {{ include "missionControl.chart" . }}
{{ include "missionControl.selectorLabels" . }}
{{- if .Chart.AppVersion }}
app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
{{- end }}
app.kubernetes.io/managed-by: {{ .Release.Service }}
{{- end }}

{{/*
Common annotations
*/}}
{{- define "missionControl.annotations" -}}
{{- if .Values.commonAnnotations }}
{{ toYaml .Values.commonAnnotations }}
{{- end }}
{{- end }}

{{/*
Common pod annotations
*/}}
{{- define "missionControl.commonPodAnnotations" -}}
{{- if .Values.commonPodAnnotations }}
{{ toYaml .Values.commonPodAnnotations }}
{{- end }}
{{- end }}

{{/*
Backend service account name.
*/}}
{{- define "missionControl.serviceAccountName" -}}
{{- if .Values.backend.serviceAccount.create -}}
{{ default (include "missionControl.fullname" .) .Values.backend.serviceAccount.name | trunc 63 | trimSuffix "-" }}
{{- else -}}
{{ default "default" .Values.backend.serviceAccount.name }}
{{- end -}}
{{- end }}

{{/*
Backend Deployment name. Referenced by the backend itself (for self-restart on
auth setup) and by the RBAC patch resourceNames.
*/}}
{{- define "missionControl.backendDeploymentName" -}}
{{ include "missionControl.fullname" . }}-backend
{{- end }}

{{/*
Frontend Deployment name.
*/}}
{{- define "missionControl.frontendDeploymentName" -}}
{{ include "missionControl.fullname" . }}-frontend
{{- end }}

{{/*
Resolve a container image reference. Pass `component` to select which entry of
`.Values.images` to use, e.g. `backendImage` or `frontendImage`.
*/}}
{{- define "missionControl.image" -}}
{{- $imageConfig := index .Values.images .component -}}
{{- if .Values.images.registry -}}
{{ .Values.images.registry }}/{{ $imageConfig.repository }}:{{ $imageConfig.tag | default .Chart.AppVersion }}
{{- else -}}
{{ $imageConfig.repository }}:{{ $imageConfig.tag | default .Chart.AppVersion }}
{{- end -}}
{{- end }}

{{/*
─── Secret name helpers ────────────────────────────────────────────────────
The application writes to fixed secret names. Centralizing them here keeps
RBAC resourceNames and the backend env wiring in sync.
*/}}

{{/*
Pre-created auth Secret containing username/password (and optional jwtSecret).
Defaults to "mission-control-auth"; overridable via auth.existingSecret.
*/}}
{{- define "missionControl.authSecretName" -}}
{{ .Values.auth.existingSecret | default "mission-control-auth" }}
{{- end }}

{{/*
Setup-token Secret used during the first-run setup flow. Generated by the
chart only when the auth Secret does not yet exist.
*/}}
{{- define "missionControl.setupTokenSecretName" -}}
{{ include "missionControl.fullname" . }}-setup-token
{{- end }}

{{/*
Draft config Secret — written by the configSave feature.
*/}}
{{- define "missionControl.draftSecretName" -}}
mission-control-draft
{{- end }}

{{/*
Deploy-feature Secrets — written when the deploy feature is enabled.
*/}}
{{- define "missionControl.deployedSecretName" -}}
mission-control-deployed
{{- end }}

{{- define "missionControl.backupSecretName" -}}
mission-control-backup
{{- end }}

{{- define "missionControl.historySecretName" -}}
mission-control-history
{{- end }}

{{/*
Alerts-feature Secrets — written when the alerts feature is enabled.
*/}}
{{- define "missionControl.alertsConfigSecretName" -}}
mission-control-alerts-config
{{- end }}

{{- define "missionControl.alertsKeySecretName" -}}
mission-control-alerts-key
{{- end }}

{{- define "missionControl.alertsLogSecretName" -}}
mission-control-alerts-log
{{- end }}

{{/*
Legacy secret names retained for the rebrand migration path. Existing
installations have secrets prefixed with `langsmith-mission-control-` from
before the rename to `mission-control`. The backend reads from the legacy
name when the new name is absent; the ClusterRole still needs update/delete
on the legacy names so the backend can migrate data and clean up.
*/}}
{{- define "missionControl.legacyDraftSecretName" -}}
langsmith-mission-control-draft
{{- end }}

{{- define "missionControl.legacyDeployedSecretName" -}}
langsmith-mission-control-deployed
{{- end }}

{{- define "missionControl.legacyBackupSecretName" -}}
langsmith-mission-control-backup
{{- end }}

{{- define "missionControl.legacyHistorySecretName" -}}
langsmith-mission-control-history
{{- end }}

{{- define "missionControl.legacyAlertsConfigSecretName" -}}
langsmith-mission-control-alerts-config
{{- end }}

{{- define "missionControl.legacyAlertsKeySecretName" -}}
langsmith-mission-control-alerts-key
{{- end }}

{{- define "missionControl.legacyAlertsLogSecretName" -}}
langsmith-mission-control-alerts-log
{{- end }}
