{
 "title": "LangSmith Services Dashboard",
 "tags": [ "LangSmith" ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   { "name": "query0" }
  ]
 },
 "panels": [
  {
   "title": "Backend Operations",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Feedback Upsert Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (le)(rate(langsmith_feedback_upsert_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le)(rate(langsmith_feedback_upsert_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le)(rate(langsmith_feedback_upsert_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Run PreFetch Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 1 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Runs Batch Size",
     "type": "barchart",
     "gridPos": { "h": 16, "w": 12, "x": 12, "y": 1 },
     "targets": [
      {
       "expr": "sum by (type)(rate(langsmith_runs_batch_count_sum[5m]))",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Trace Fetching Latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 0, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le, hit)(rate(smith_prefetch_traces_time_bucket[5m]))\n)",
       "legendFormat": "p99"
      }
     ]
    },
    {
     "title": "Latency of checking Alerts for Batch of Feedback",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 6, "x": 6, "y": 9 },
     "targets": [
      {
       "expr": "histogram_quantile(\n  0.50,\n  sum by (le, hit)(rate(langsmith_feedback_alerts_check_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p50"
      },
      {
       "expr": "histogram_quantile(\n  0.95,\n  sum by (le, hit)(rate(langsmith_feedback_alerts_check_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p95"
      },
      {
       "expr": "histogram_quantile(\n  0.99,\n  sum by (le, hit)(rate(langsmith_feedback_alerts_check_latency_seconds_bucket[5m]))\n)",
       "legendFormat": "p99"
      }
     ]
    }
   ]
  },
  { "title": "Platform Backend Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "P50 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.50, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "P50 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.50, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "P50 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.50, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"platform-backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  { "title": "Backend Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Request Latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.50, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m])))",
     "legendFormat": "p50"
    },
    {
     "expr": "histogram_quantile(0.90, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m])))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.99, sum by (le) (rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m])))",
     "legendFormat": "p99"
    }
   ]
  },
  {
   "title": "P50 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 0, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.50, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "P90 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 8, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.90, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "P99 Endpoint Latency",
   "type": "gauge",
   "gridPos": { "h": 12, "w": 8, "x": 16, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "topk(10, histogram_quantile(0.99, sum by (path,le)(rate(langsmith_http_requests_latency_seconds_bucket{app_name=\"backend\"}[5m]))))",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "Postgres Pool Avg Connections Use",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(langsmith_pg_pool_used_sum[2m])) / sum(rate(langsmith_pg_pool_used_count[2m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Postgres Pool Avg Connections Idle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(langsmith_pg_pool_idle_sum[2m])) / sum(rate(langsmith_pg_pool_idle_count[2m]))",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  { "title": "HTTP Requests", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 57 } },
  {
   "title": "Total Requests by Service",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 58 },
   "targets": [
    {
     "expr": "sum by (k8s_service) (\n  rate(langsmith_http_requests_total[2m])\n)",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "Requests in Progress by Pod",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 58 },
   "targets": [
    {
     "expr": "sum by (k8s_pod) (langsmith_http_requests_in_progress)",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "Total Requests by Pod",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 67 },
   "targets": [
    {
     "expr": "sum by (k8s_pod) (\n  rate(langsmith_http_requests_total[2m])\n)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Requests in Progress by Service",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 68 },
   "targets": [
    {
     "expr": "sum by (k8s_service) (langsmith_http_requests_in_progress)",
     "legendFormat": "{{k8s_service}}"
    }
   ]
  },
  {
   "title": "Request Size per service",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (k8s_service) (rate(langsmith_http_requests_size_bytes_sum[2m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Size per Pod",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 77 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (k8s_pod) (rate(langsmith_http_requests_size_bytes_sum[2m]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}